#!/bin/sh

LOG_DIR='/mnt/fuelphp/fuel/'

LOG_FILE=`find "$LOG_DIR"app/\logs -type f -name "*.php" | sort -n | tail -1 | cut -f2- -d" "`
echo ==============='SHOWING FUEL ERROR LOG ==============='
echo $LOG_FILE
echo '====================================================='
tail -f "$LOG_FILE"